version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g yarn
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - yarn install --production --ignore-scripts --prefer-offline
      - mkdir target
      - mv .ebextensions target
      - mv bin target
      - mv node_modules target
      - mv build target

artifacts:
  base-directory: 'target'
  files:
    - '**/*'